AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.icabot.ToDoList.StreamLambdaHandler::handleRequest
      Runtime: java11
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Role: #add ARN
      Tracing: Active
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY